[hololens]
package = "holo/lens-sencha-app"

[hololens.sencha]
app = "SparkClassroomTeacher"

[hololens.input]
root = "sencha-workspace"
files = [
    "SparkClassroomTeacher/**",
    "packages/jarvus-routing/**",
    "packages/spark-theme/**",
    "packages/spark-classroom/**",
    "packages/slate-core-data/**",
    "packages/emergence-apikit/**",
    "packages/jarvus-apikit/**",
    "packages/jarvus-touch-accordion/**",
    "packages/jarvus-gridheight/**",
    "packages/jarvus-fuzzytime/**",
    "packages/jarvus-hotfixes/**",
    "ext/**",
    "workspace.json",
]

[hololens.output]
root = "webapp-builds/SparkClassroomTeacher"
merge = "replace"