<?php

if (isset($_GET['url'])) {
    $host = parse_url($_GET['url'])['host'];

    if (!host) {
        die('Invalid URL');
    }

    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $_GET['url']);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2401.0 Safari/537.36');
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 3);

    $html = curl_exec($ch);
    $realUrl = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);
    $host = parse_url($realUrl)['host'];

    $dom = new DOMDocument;
    @$dom->loadHTML($html);
    $title = $dom->getElementsByTagName('title')->item('0')->nodeValue;

    foreach ($dom->getElementsByTagName('link') as $link) {
        $rel = $link->getAttribute('rel');

        if ($rel == 'icon' || $rel == 'shortcut icon') {
            $iconUrl = $link->getAttribute('href');

            if (substr($iconUrl, 0, 4) !== 'http') {
                $iconUrl = "http://$host/$iconUrl";
            }
            break;
        }
    }

    foreach ($dom->getElementsByTagName('meta') as $meta) {
        if ($meta->getAttribute('name') == 'description') {
            $description = $meta->getAttribute('content');
            break;
        }
    }

    if (!$iconUrl) {
        $iconUrl = 'http://' . $host . '/favicon.ico';
        curl_setopt($ch, CURLOPT_NOBODY, true);
        curl_setopt($ch, CURLOPT_URL, $iconUrl);
        curl_exec($ch);
        $contentType = curl_getinfo($ch, CURLINFO_CONTENT_TYPE);
        curl_close($ch);

        if (substr($contentType, 0, 5) != 'image') {
            $iconUrl = null;
        }
    }

    print json_encode([
        'title' => $title,
        'icon' => $iconUrl,
        'description' => $description ? $description : 'Auto-generated by SparkPoint Manager',
    ], JSON_PRETTY_PRINT);
}